### PR TITLE
Reading NIDM-Results packs and SPM-generated json serialisation

### PR DESCRIPTION
**Pull request by TomMaullin**
The viewer should now be compatible with the latest NIDM-Results packs (i.e. with the json or jsonld inside the zip).

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @TomMaullin: I have updated the title of this PR, feel free to modify it again if needed. Is this PR ready for review?

**Comment by TomMaullin** [comment]
Hi @cmaumet Yes this is ready to review! It also now works with the FSL format with jsons inside the zip.

**Comment by cmaumet** [comment]
Hi @TomMaullin! Thank you for this! Have you tested the code with an empty `test/data` directory? When I try, I get the following error:
```
>> runTest
Running testFeatures

================================================================================
Error occurred in testFeatures/checkViewerRunsSPM and it did not run to completion.

    ---------
    Error ID:
    ---------
    'MATLAB:fileread:cannotOpenFile'

    --------------
    Error Details:
    --------------
    Error using fileread (line 22)
    Could not open file
    /Users/cmaumet/Projects/Data_sharing/dev/nidmresults-spmhtml/test/../test/data/ex_spm_default.nidm/nidm.json.
    Cannot open file. Existence? Permissions? Memory? . . ..
    
    Error in nidm_results_display (line 30)
            jsondoc=spm_jsonread(jsonfilepath);
    
    Error in testFeatures/checkViewerRunsSPM (line 31)
                nidm_results_display(data_path);
================================================================================
.
================================================================================
Error occurred in testFeatures/checkForTitle and it did not run to completion.
```

The `nidm.json` file is indeed missing in the `/Users/cmaumet/Projects/Data_sharing/dev/nidmresults-spmhtml/test/../test/data/ex_spm_default.nidm` folder so I am wondering if the right test data is downloaded from NeuroVault?

Can you have a look and let me know if you can reproduce the issue on your machine?

**Comment by TomMaullin** [comment]
The tests should now be updated. 

In terms of future development there are a few footnotes. I shall list them here and also copy them into the readme.md so that they can easily be located when the next SPM update or NIDM-export update occurs.

##### Notes for future development

1. Currently (as of 19/03/2017), there is a bug in the NIDM-export for SPM which means that attributes with the prefix `nidm_` inside the jsonld have an additional `:` character appended on the end. This has been fixed and should be updated in the next SPM update. However, until then, in the viewer there is some additional code removing these colons. This code can be found in the `nidm_results_display` code specifically in lines nidm_results_display.m#L26 and nidm_results_display.m#L124 onwards.

1. Presently (as of 19/03/2017), both FSL and SPM export NIDM-Results in the prov jsonld format. However, although both of these follow the same guidelines, the export for these packs is very different. The viewer currently supports NIDM-Results packs generated by the FSL-format that contain either a single excursion set or multiple excursion sets. 

However, the viewer only supports SPM-formatted NIDM-Results packs containing a SINGLE excursion set. This is simply as SPM only exports single contrast NIDM-Results packs currently. However, if in the future another software supports NIDM-Results export and follows the SPM NIDM export format and exports multiple contrasts, the viewer will not be able to display the export. Currently, this is not an issue but it is something to be aware of, should more softwares adopt NIDM-Results.

**Comment by cmaumet** [comment]
Hi @TomMaullin. If you have some time could you have a quick look at this? I just tried to run the tests on this PR but I get the following errors:
```
Failure Summary:

     Name                                  Failed  Incomplete  Reason(s)
    =====================================================================
     testDataSets/test_ex_spm_default        X         X       Errored.
    ---------------------------------------------------------------------
     testFeatures/checkViewerRunsSPM         X         X       Errored.
    ---------------------------------------------------------------------
     testFeatures/checkForTitle              X         X       Errored.
    ---------------------------------------------------------------------
     testFeatures/checkViewerRunsSPMwoMIP    X         X       Errored.
```

**Comment by TomMaullin** [comment]
Hi Camille,

I have looked into your errors and 3 of the 4 are caused by a missing json on Neurovault in this pack:

https://neurovault.org/collections/1692/ex_spm_default.nidm

The other error 'checkViewerRunsSPMwoMIP' is caused by a local json I must have had only on my machine for some reason which has had it's MIP removed. I shall write some code that creates a json without an MIP using one of the other NIDM packs to replace this test today.

**Comment by cmaumet** [comment]
Hi @TomMaullin! Thanks for looking into this! Yes, if you could update the code/tests to make sure that all the tests pass that would be great. (I've been working on an update for compatibility with SnPM that I'll send as a PR once this one is merged.)

**Comment by TomMaullin** [comment]
Hi @cmaumet, I believe I have now fixed the errors you were having with the tests. Please let me know though if you have any further issues on your machine!

**Comment by TomMaullin** [comment]
Hi @cmaumet, I've made a tiny edit so that this now displays the NIDM-Results pack information in the footer of the page as requested in issue #16 - this PR should now be fine to go!

**Pull request merged**
