### PR TITLE
NaN removal

### PR DESCRIPTION
**Pull request by TomMaullin**
Hi @cmaumet , This PR addresses #32 by removing columns of NaN's in the table of peak values! Please let me know what you think! My test log is below:

```
  1×32 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration
    Details

Totals:
   32 Passed, 0 Failed, 0 Incomplete.
   77.5135 seconds testing time.
```

### CODE REVIEW

**Comment by cmaumet** [comment]
Thanks @TomMaullin! I will have a look shortly. Can you double check your configuration of git, your commits are still not linked to your GitHub account (cf. https://github.com/incf-nidash/nidmresults-spmhtml/pull/29#issuecomment-359776922).

**Comment by TomMaullin** [comment]
Hi @cmaumet, Ah yes I'll do this now!

**Comment by cmaumet** [comment]
@TomMaullin: Are you fine with me closing this PR now that you have open #36?

**Comment by TomMaullin** [comment]
@cmaumet That's fine by me!

**Pull request closed without merging**
